package jp.co.smartservice.app.common.entity;

import java.io.Serializable;
import java.util.Date;

public class T001User implements Serializable {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t001_user.user_id
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	private String userId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t001_user.password
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	private String password;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t001_user.name_kanji
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	private String nameKanji;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t001_user.name_katakana
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	private String nameKatakana;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t001_user.gender
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	private String gender;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t001_user.birthday
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	private String birthday;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t001_user.joined_date
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	private String joinedDate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t001_user.email
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	private String email;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t001_user.address
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	private String address;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t001_user.tel_no
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	private String telNo;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t001_user.kyk_type
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	private String kykType;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t001_user.job_stat
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	private String jobStat;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t001_user.user_role
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	private String userRole;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t001_user.del_flg
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	private String delFlg;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t001_user.insert_date
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	private Date insertDate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t001_user.update_date
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	private Date updateDate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table t001_user
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t001_user.user_id
	 * @return  the value of t001_user.user_id
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t001_user.user_id
	 * @param userId  the value for t001_user.user_id
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t001_user.password
	 * @return  the value of t001_user.password
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t001_user.password
	 * @param password  the value for t001_user.password
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t001_user.name_kanji
	 * @return  the value of t001_user.name_kanji
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	public String getNameKanji() {
		return nameKanji;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t001_user.name_kanji
	 * @param nameKanji  the value for t001_user.name_kanji
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	public void setNameKanji(String nameKanji) {
		this.nameKanji = nameKanji;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t001_user.name_katakana
	 * @return  the value of t001_user.name_katakana
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	public String getNameKatakana() {
		return nameKatakana;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t001_user.name_katakana
	 * @param nameKatakana  the value for t001_user.name_katakana
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	public void setNameKatakana(String nameKatakana) {
		this.nameKatakana = nameKatakana;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t001_user.gender
	 * @return  the value of t001_user.gender
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	public String getGender() {
		return gender;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t001_user.gender
	 * @param gender  the value for t001_user.gender
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	public void setGender(String gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t001_user.birthday
	 * @return  the value of t001_user.birthday
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	public String getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t001_user.birthday
	 * @param birthday  the value for t001_user.birthday
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t001_user.joined_date
	 * @return  the value of t001_user.joined_date
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	public String getJoinedDate() {
		return joinedDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t001_user.joined_date
	 * @param joinedDate  the value for t001_user.joined_date
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	public void setJoinedDate(String joinedDate) {
		this.joinedDate = joinedDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t001_user.email
	 * @return  the value of t001_user.email
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t001_user.email
	 * @param email  the value for t001_user.email
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t001_user.address
	 * @return  the value of t001_user.address
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t001_user.address
	 * @param address  the value for t001_user.address
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t001_user.tel_no
	 * @return  the value of t001_user.tel_no
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	public String getTelNo() {
		return telNo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t001_user.tel_no
	 * @param telNo  the value for t001_user.tel_no
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	public void setTelNo(String telNo) {
		this.telNo = telNo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t001_user.kyk_type
	 * @return  the value of t001_user.kyk_type
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	public String getKykType() {
		return kykType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t001_user.kyk_type
	 * @param kykType  the value for t001_user.kyk_type
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	public void setKykType(String kykType) {
		this.kykType = kykType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t001_user.job_stat
	 * @return  the value of t001_user.job_stat
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	public String getJobStat() {
		return jobStat;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t001_user.job_stat
	 * @param jobStat  the value for t001_user.job_stat
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	public void setJobStat(String jobStat) {
		this.jobStat = jobStat;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t001_user.user_role
	 * @return  the value of t001_user.user_role
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	public String getUserRole() {
		return userRole;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t001_user.user_role
	 * @param userRole  the value for t001_user.user_role
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	public void setUserRole(String userRole) {
		this.userRole = userRole;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t001_user.del_flg
	 * @return  the value of t001_user.del_flg
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	public String getDelFlg() {
		return delFlg;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t001_user.del_flg
	 * @param delFlg  the value for t001_user.del_flg
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	public void setDelFlg(String delFlg) {
		this.delFlg = delFlg;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t001_user.insert_date
	 * @return  the value of t001_user.insert_date
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	public Date getInsertDate() {
		return insertDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t001_user.insert_date
	 * @param insertDate  the value for t001_user.insert_date
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t001_user.update_date
	 * @return  the value of t001_user.update_date
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t001_user.update_date
	 * @param updateDate  the value for t001_user.update_date
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t001_user
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (!(that instanceof T001User)) {
			return false;
		}
		T001User other = (T001User) that;
		return this.getUserId() == null ? other == null
				: this.getUserId().equals(other.getUserId()) && this.getPassword() == null ? other == null
						: this.getPassword().equals(other.getPassword()) && this.getNameKanji() == null ? other == null
								: this.getNameKanji().equals(other.getNameKanji()) && this.getNameKatakana() == null
										? other == null
										: this.getNameKatakana().equals(other.getNameKatakana())
												&& this.getGender() == null
														? other == null
														: this.getGender().equals(other.getGender())
																&& this.getBirthday() == null
																		? other == null
																		: this.getBirthday().equals(other.getBirthday())
																				&& this.getJoinedDate() == null
																						? other == null
																						: this.getJoinedDate()
																								.equals(other
																										.getJoinedDate())
																								&& this.getEmail() == null
																										? other == null
																										: this.getEmail()
																												.equals(other
																														.getEmail())
																												&& this.getAddress() == null
																														? other == null
																														: this.getAddress()
																																.equals(other
																																		.getAddress())
																																&& this.getTelNo() == null
																																		? other == null
																																		: this.getTelNo()
																																				.equals(other
																																						.getTelNo())
																																				&& this.getKykType() == null
																																						? other == null
																																						: this.getKykType()
																																								.equals(other
																																										.getKykType())
																																								&& this.getJobStat() == null
																																										? other == null
																																										: this.getJobStat()
																																												.equals(other
																																														.getJobStat())
																																												&& this.getUserRole() == null
																																														? other == null
																																														: this.getUserRole()
																																																.equals(other
																																																		.getUserRole())
																																																&& this.getDelFlg() == null
																																																		? other == null
																																																		: this.getDelFlg()
																																																				.equals(other
																																																						.getDelFlg())
																																																				&& this.getInsertDate() == null
																																																						? other == null
																																																						: this.getInsertDate()
																																																								.equals(other
																																																										.getInsertDate())
																																																								&& this.getUpdateDate() == null
																																																										? other == null
																																																										: this.getUpdateDate()
																																																												.equals(other
																																																														.getUpdateDate());
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t001_user
	 * @ibatorgenerated  Fri Sep 25 22:39:47 JST 2015
	 */
	@Override
	public int hashCode() {
		int hash = 23;
		if (getUserId() != null) {
			hash *= getUserId().hashCode();
		}
		if (getPassword() != null) {
			hash *= getPassword().hashCode();
		}
		if (getNameKanji() != null) {
			hash *= getNameKanji().hashCode();
		}
		if (getNameKatakana() != null) {
			hash *= getNameKatakana().hashCode();
		}
		if (getGender() != null) {
			hash *= getGender().hashCode();
		}
		if (getBirthday() != null) {
			hash *= getBirthday().hashCode();
		}
		if (getJoinedDate() != null) {
			hash *= getJoinedDate().hashCode();
		}
		if (getEmail() != null) {
			hash *= getEmail().hashCode();
		}
		if (getAddress() != null) {
			hash *= getAddress().hashCode();
		}
		if (getTelNo() != null) {
			hash *= getTelNo().hashCode();
		}
		if (getKykType() != null) {
			hash *= getKykType().hashCode();
		}
		if (getJobStat() != null) {
			hash *= getJobStat().hashCode();
		}
		if (getUserRole() != null) {
			hash *= getUserRole().hashCode();
		}
		if (getDelFlg() != null) {
			hash *= getDelFlg().hashCode();
		}
		if (getInsertDate() != null) {
			hash *= getInsertDate().hashCode();
		}
		if (getUpdateDate() != null) {
			hash *= getUpdateDate().hashCode();
		}
		return hash;
	}
}