package jp.co.smartservice.fw.dao;

import java.util.List;
import jp.co.smartservice.app.common.entity.T001User;
import jp.co.smartservice.app.common.entity.T001UserExample;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class T001UserDAOImpl extends SqlMapClientDaoSupport implements T001UserDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t001_user
     *
     * @ibatorgenerated Fri Sep 25 22:39:47 JST 2015
     */
    public T001UserDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t001_user
     *
     * @ibatorgenerated Fri Sep 25 22:39:47 JST 2015
     */
    public int countByExample(T001UserExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t001_user.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t001_user
     *
     * @ibatorgenerated Fri Sep 25 22:39:47 JST 2015
     */
    public int deleteByExample(T001UserExample example) {
        int rows = getSqlMapClientTemplate().delete("t001_user.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t001_user
     *
     * @ibatorgenerated Fri Sep 25 22:39:47 JST 2015
     */
    public int deleteByPrimaryKey(String userId) {
        T001User key = new T001User();
        key.setUserId(userId);
        int rows = getSqlMapClientTemplate().delete("t001_user.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t001_user
     *
     * @ibatorgenerated Fri Sep 25 22:39:47 JST 2015
     */
    public void insert(T001User record) {
        getSqlMapClientTemplate().insert("t001_user.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t001_user
     *
     * @ibatorgenerated Fri Sep 25 22:39:47 JST 2015
     */
    public void insertSelective(T001User record) {
        getSqlMapClientTemplate().insert("t001_user.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t001_user
     *
     * @ibatorgenerated Fri Sep 25 22:39:47 JST 2015
     */
    @SuppressWarnings("unchecked")
    public List<T001User> selectByExample(T001UserExample example) {
        List<T001User> list = getSqlMapClientTemplate().queryForList("t001_user.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t001_user
     *
     * @ibatorgenerated Fri Sep 25 22:39:47 JST 2015
     */
    public T001User selectByPrimaryKey(String userId) {
        T001User key = new T001User();
        key.setUserId(userId);
        T001User record = (T001User) getSqlMapClientTemplate().queryForObject("t001_user.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t001_user
     *
     * @ibatorgenerated Fri Sep 25 22:39:47 JST 2015
     */
    public int updateByExampleSelective(T001User record, T001UserExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t001_user.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t001_user
     *
     * @ibatorgenerated Fri Sep 25 22:39:47 JST 2015
     */
    public int updateByExample(T001User record, T001UserExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t001_user.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t001_user
     *
     * @ibatorgenerated Fri Sep 25 22:39:47 JST 2015
     */
    public int updateByPrimaryKeySelective(T001User record) {
        int rows = getSqlMapClientTemplate().update("t001_user.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t001_user
     *
     * @ibatorgenerated Fri Sep 25 22:39:47 JST 2015
     */
    public int updateByPrimaryKey(T001User record) {
        int rows = getSqlMapClientTemplate().update("t001_user.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t001_user
     *
     * @ibatorgenerated Fri Sep 25 22:39:47 JST 2015
     */
    private static class UpdateByExampleParms extends T001UserExample {
        private Object record;

        public UpdateByExampleParms(Object record, T001UserExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}