package jp.co.smartservice.fw.dao;

import java.util.List;
import jp.co.smartservice.app.common.entity.T001User;
import jp.co.smartservice.app.common.entity.T001UserExample;

public interface T001UserDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t001_user
     *
     * @ibatorgenerated Fri Sep 25 22:39:47 JST 2015
     */
    int countByExample(T001UserExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t001_user
     *
     * @ibatorgenerated Fri Sep 25 22:39:47 JST 2015
     */
    int deleteByExample(T001UserExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t001_user
     *
     * @ibatorgenerated Fri Sep 25 22:39:47 JST 2015
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t001_user
     *
     * @ibatorgenerated Fri Sep 25 22:39:47 JST 2015
     */
    void insert(T001User record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t001_user
     *
     * @ibatorgenerated Fri Sep 25 22:39:47 JST 2015
     */
    void insertSelective(T001User record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t001_user
     *
     * @ibatorgenerated Fri Sep 25 22:39:47 JST 2015
     */
    List<T001User> selectByExample(T001UserExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t001_user
     *
     * @ibatorgenerated Fri Sep 25 22:39:47 JST 2015
     */
    T001User selectByPrimaryKey(String userId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t001_user
     *
     * @ibatorgenerated Fri Sep 25 22:39:47 JST 2015
     */
    int updateByExampleSelective(T001User record, T001UserExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t001_user
     *
     * @ibatorgenerated Fri Sep 25 22:39:47 JST 2015
     */
    int updateByExample(T001User record, T001UserExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t001_user
     *
     * @ibatorgenerated Fri Sep 25 22:39:47 JST 2015
     */
    int updateByPrimaryKeySelective(T001User record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t001_user
     *
     * @ibatorgenerated Fri Sep 25 22:39:47 JST 2015
     */
    int updateByPrimaryKey(T001User record);
}